# .github/workflows/update_rtt_data.yml
name: Update RTT Data

on:
  schedule:
    - cron: '0 8 1 * *'  # 8am on 1st of every month
  workflow_dispatch:
    inputs:
      month:
        description: 'Month (e.g. Jan, Feb)'
      year:
        description: 'Year (e.g. 2026)'
        required: true

jobs:
  update-data:
    environment:
      name: demo-secrets
    runs-on: ubuntu-latest
    env:
      MONTH: ${{ github.event.inputs.month }}
      YEAR: ${{ github.event.inputs.year }}
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      DATABRICKS_API_KEY: ${{ secrets.DATABRICKS_API_KEY }}
      DATABRICKS_DATA_DIR: ${{ secrets.DATABRICKS_DATA_DIR }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - run: pip install httpx polars beautifulsoup4 databricks-sdk

      - run: python -m scripts.etl
